### ISSUE TITLE
Repository not found

### ISSUE THREAD

**Issue by s3eed-dw** [ethicalhackeragnidhra/viSQL#1]
ython installer.py
Cloning into '/usr/share/visql'...
Username for 'https://github.com': zzzz
Password for 'https://zzzz@github.com': 
remote: Repository not found.
fatal: repository 'https://github.com/blackvkng/viSQL.git/' not found
Traceback (most recent call last):
  File "installer.py", line 38, in <module>
    main()
  File "installer.py", line 23, in main
    pip.main(["install", i])
AttributeError: 'module' object has no attribute 'main'

**Comment by GDATTACKER-RESEARCHER** [comment]
same
